### ISSUE TITLE
No such file or directory: './settings/scores.txt'

### ISSUE THREAD

**Issue by theangrybagel** [Pella86/Snake4d#2]
I'm using linux with python 3.7. This is what happens when I run the program:

~/Documents/Snake4d on master`
python3 main.py
Snake 4D (2.0)
Traceback (most recent call last):
  File "main.py", line 430, in <module>
    main()
  File "main.py", line 410, in main
    mapp = MainApp(root)
  File "main.py", line 180, in __init__
    self.score_board = score.ScoreBoard(self.root)
  File "./src/score.py", line 115, in __init__
    self.scores = Scores()
  File "./src/score.py", line 65, in __init__
    self.read_scores()
  File "./src/score.py", line 70, in read_scores
    with open(self.filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: './settings/scores.txt'
`

**Comment by theangrybagel** [comment]
I fixed this by commenting out lines 68 - 74 in ./src/scores.py, running the game, and then uncommenting the code after running it once.

**Comment by Pella86** [comment]
Hi, thank you for reporting the issue, I think one has to create in the game folder the settings folder, I will look into it, I have in mind a fix, namely create the file at the start of the game if it doesn't exist.

**Comment by Pella86** [comment]
Solved in commit cdf3773b42efc888affa33dd22ebe56a48f6d979 (16.06.20)
